# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/hi3660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter stanford victoria,$(TARGET_DEVICE)),)

endif
